server:
  port: 8081
spring:
  application:
    name: deal
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/credit_neoflex
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: validate
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: myGroup

  liquibase:
    change-log: db/changelog/main-changelog.xml


