version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.11.amd64
    container_name: zookeeper
    ports:
      - "2181:2181"
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:5.5.11.amd64
    container_name: kafka
    ports:
      - "9092:9092"
    restart: always
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  PostgreSQL:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=credit_neoflex

  statement:
    container_name: statement
    build: statement
    ports:
      - 8082:8082

  calculator:
    container_name: calculator
    build: calculator
    ports:
      - 8080:8080
  gateway:
    container_name: gateway
    build: gateway
    ports:
      - 8088:8088
  dossier:
    container_name: dossier
    build: dossier
    ports:
      - 8000:8000
    environment:
      KAFKA_SERVER: kafka:9092
    depends_on:
      - kafka
  deal:
    container_name: deal
    build: deal
    ports:
      - 8081:8081
    depends_on:
      - PostgreSQL
      - kafka
    environment:
      - SPRING_DATASOURCE_URL= ${DB_URL}
      - SPRING_DATASOURCE_USERNAME= ${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD= ${DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update