version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  PostgreSQL:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=credit_neoflex

  statement:
    container_name: statement
    build: statement
    ports:
      - 8082:8082

  calculator:
    container_name: calculator
    build: calculator
    ports:
      - 8080:8080

  dossier:
    container_name: dossier
    build: dossier
    ports:
      - 8000:8000
    environment:
      KAFKA_SERVER: kafka:9092
    depends_on:
      - kafka
  deal:
    container_name: deal
    build: deal
    ports:
      - 8081:8081
    depends_on:
      - PostgreSQL
      - kafka
    environment:
      - SPRING_DATASOURCE_URL= jdbc:postgresql://PostgreSQL:5432/credit_neoflex
      - SPRING_DATASOURCE_USERNAME=
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update