spring:
  application:
    name: dossier
  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    host: smtp.mail.ru
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: myGroup
server:
  port: 8000