spring:
  application:
    name: dossier
  mail:
    username: 
    password:
    host: smtp.mail.ru
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: myGroup
server:
  port: 8000