name: Java CI with Maven

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build Statement with Maven
        working-directory: ./statement
        run: mvn -B clean install --file pom.xml

      - name: Build Calculator with Maven
        working-directory: ./calculator
        run: mvn -B clean install --file pom.xml

      - name: Build Deal with Maven
        working-directory: ./deal
        run: mvn -B clean install --file pom.xml -DskipTests

      - name: Build Dossier with Maven
        working-directory: ./dossier
        run: mvn -B clean install --file pom.xml -DskipTests

      - name: Build Gateway with Maven
        working-directory: ./gateway
        run: mvn -B clean install --file pom.xml
  tests:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Set up JDK 17
          uses: actions/setup-java@v4
          with:
            java-version: '17'
            distribution: 'temurin'

        - name: Maven Verify Calculator
          working-directory: ./calculator
          run: mvn -B clean verify

        - name: Test Coverage Calculator
          uses: codecov/codecov-action@v3
          with:
            directory: ./calculator
            token: ${{ secrets.CODECOV_TOKEN }}
            flags: Calculator

        - name: Maven Verify Statement
          working-directory: ./statement
          run: mvn -B clean verify

        - name: Test Coverage Statement
          uses: codecov/codecov-action@v3
          with:
            directory: ./statement
            token: ${{ secrets.CODECOV_TOKEN }}
            flags: Statement